blueprint:
  name: IKEA Bilresa Remote (Direct Device Trigger)
  description: Automation made for IKEA Bilresa (E2489) based on Zigbee2MQTT actions.
  domain: automation
  input:
    remote_device:
      name: Bilresa Remote
      description: Select your Bilresa 2-button remote from Zigbee2MQTT.
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: "BILRESA remote control with buttons"
    action_on:
      name: Button 1 (On)
      default: []
      selector:
        action: {}
    action_off:
      name: Button 0 (Off)
      default: []
      selector:
        action: {}
    action_on_double:
      name: Button 1 (Double click)
      default: []
      selector:
        action: {}
    action_off_double:
      name: Button 0 (Double click)
      default: []
      selector:
        action: {}
    action_up:
      name: Button 1 (Hold/Step)
      default: []
      selector:
        action: {}
    action_down:
      name: Button 0 (Hold/Step)
      default: []
      selector:
        action: {}
    action_stop:
      name: Stop (Release)
      description: Action when releasing a button after being held.
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "on"
    id: "on"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "off"
    id: "off"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "on_double"
    id: "on_double"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "off_double"
    id: "off_double"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_move_up"
    id: "up"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_move_down"
    id: "down"
  - platform: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_stop"
    id: "stop"

action:
  - choose:
      - conditions: "{{ trigger.id == 'on' }}"
        sequence: !input action_on
      - conditions: "{{ trigger.id == 'off' }}"
        sequence: !input action_off
      - conditions: "{{ trigger.id == 'on_double' }}"
        sequence: !input action_on_double
      - conditions: "{{ trigger.id == 'off_double' }}"
        sequence: !input action_off_double
      - conditions: "{{ trigger.id == 'up' }}"
        sequence: !input action_up
      - conditions: "{{ trigger.id == 'down' }}"
        sequence: !input action_down
      - conditions: "{{ trigger.id == 'stop' }}"
        sequence: !input action_stop